# Generated by Django 5.0.6 on 2024-06-14 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="working_on",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="api.order"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="api.order",
            ),
        ),
    ]
