# Generated by Django 5.0.6 on 2024-06-14 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_employee_working_on_alter_trip_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="working_on",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.order",
            ),
        ),
    ]
